eclipse-mosaic/mosaic

pom.xml
Signed-off-by: Felix Hilgerdenaar <felix.hilgerdenaar@fokus.fraunhofer.de>
* generation of apidocs by JavaDoc
* generation triggered by `mvn site`
* generate aggregated apidocs at root level only and omit testapidocs
* issue 37
No parts are affected.
=> JavaDoc generation by 'mvn site'

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/geo/CartesianPolygon.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/geo/GeoPolygon.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/MathUtils.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/geo/PolygonTest.java
Signed-off-by: Pablo Osinaga <pablo.alberto.osinaga@fokus.fraunhofer.de>
Replace current implementation of the `contains` method in the `CartesianPolygon` class with a [PNPOLY algorithm](https://wrf.ecse.rpi.edu/Research/Short_Notes/pnpoly.html) implementation.
Resolves internal issue 47.
No.
=> fix(geomath): CartesianPolygon contains

bundle/src/assembly/resources/fed/ns3/ns3_installer.sh
Python2 already reached EOL in January. This PR adjusts the ns3_installer.sh script to use python3 instead of python2
=> Use python3 in ns3_installer.sh

NOTICE-THIRD-PARTY.md, lib/mosaic-docker/pom.xml, pom.xml, rti/mosaic-rti-api/pom.xml
This PR removes the depedencies for `slf4j-api`, `commons-lang3`, and `findbugs-annotations` from the parent pom.xml and adds them to the modules which requires them.
* Link to [Eclipse Mosaic repository](https://github.com/eclipse/mosaic/issues) issue
=> Removed Transitive dependencies from parent POM

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/traci/SumoVersion.java, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
This PR upgrades code and CI to work with new stable version of SUMO 1.8.0
* All tests are successful, no need to adjust code to be compatible with the new version.
* The docker image used by the Jenkins pipeline has been upgraded to use SUMO 1.8.0 as well (https://hub.docker.com/r/eclipsemosaic/mosaic-ci/tags). The Dockerfile used for this image is now part of this repository.
* - 
Yes, will be updated asap.
=> Upgrade to SUMO 1.8.0

fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/ambassador/SimulationEntities.java, fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/ambassador/SimulationNode.java, fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/ambassador/SnsAmbassador.java, fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/ambassador/TransmissionSimulator.java, fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/model/SophisticatedAdhocTransmissionModel.java, fed/mosaic-sns/src/test/java/org/eclipse/mosaic/fed/sns/model/AdhocTransmissionModelTest.java
SNS uses `GeoPoint` and `GeoArea` to check for reachability of nodes. This is highly inefficient. Using `CartesianPoint` and `CartesianArea` instead improves performance by factor 5.
-
No
=> Use cartesian geometry in SNS to check reachability

fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/SpawningFramework.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/TrafficLightSpawner.java, fed/mosaic-mapping/src/main/resources/CMappingAmbassadorScheme.json, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/ambassador/SpawningFrameworkTrafficLightTest.java, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/config/DepartSpeedTest.java, fed/mosaic-mapping/src/test/resources/mapping/departspeed.json
- It is now possible to add multiple apps distributed by weights to traffic lights. If the parameters"weight" and "tlGroupId" in the traffic light mapping, then the default value of the weight is 1. 
- The mapping schema was adapted, so that weights in the traffic light mapping can be bigger than 1
* Resolves issue #35
Traffic light documentation in docs/simulators/application_simulator/
=> Resolves "Mapping - Add Apps to all TrafficLights"

app/tutorials/highway-management/src/main/java/org/eclipse/mosaic/app/tutorial/HighwayManagementApp.java, lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/persistence/SQLiteLoader.java, lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/route/Edge.java, lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/route/Route.java, lib/mosaic-database/src/test/java/org/eclipse/mosaic/lib/database/route/RouteTest.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/database/RouteManager.java, lib/mosaic-routing/src/test/java/org/eclipse/mosaic/lib/routing/database/RouteManagerTest.java
If the scenario database was created from a Netfile, the exported rou.xml from both scenario-convert and SumoAmbassador are invalid. While importing a net.xml file, each Sumo-Edge of the network is transformed to one Connection. Points which form the geometry/shape of the edge, are added to the connection as Nodes.
When exporting Routes, however, the geometry nodes from a Connection are transformed to multiple edges (e.g. a connection with 2 additional geometry nodes would result in 3 edges). This is only valid, as long as the database was created from OSM input file. When coming from a SUMO network file, the routes must be exported in a way, that each connection results in only one corresponding edge.
This issue is fixed in this PR. When transforming the `Route` from the database into a …
=> Fixed issue with database which was created from Network file

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/AStar.java
Signed-off-by: Franziska Vogt <franziska.vogt@fokus.fraunhofer.de>
This pull request fixes a bug, which caused a failure to build a route given specific vehicle spawning orders.
* Link to [Eclipse Mosaic Extended repository](https://gitlab.fokus.fraunhofer.de/simulation/mosaic/mosaic-extended/-/issues/149) issue 
None
=> Fixed route building by clearing all lists at start

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/traci/SumoVersion.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/traci/commands/TrafficLightAddProgramTest.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/traci/junit/SinceSumo.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/traci/junit/SumoTraciRule.java, test/ci/ci-image-mvn-sumo/README.md
Upgrade to SUMO 1.9.0
- Deployed new image for Eclipse CI with SUMO 1.9.0
- Added `@SinceSumo`  annotation for tests to be executed only if specific SUMO version is installed
- Fixed test `TrafficLightAddProgramTest`. Due to a fix in SUMO, traffic lights now start with the first phase defined in the program when switching to it. This was not the case in previous versions of SUMO. As a consequence, the assertion of the states of the traffic light at specific simulations times had to be adjusted to the now correct behavior.
* Internal issue 151 
The latest supported version should be fixed in the documentation.
=> Upgrade SUMO support to 1.9.0

Jenkinsfile, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
The docker image which is used to run tests with Maven is now configured with a specific user, allowing the m2-repository to be created again.
=> Fixed issue that Docker image could not create m2 repository

bundle/src/assembly/resources/etc/runtime.json, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/communication/AdHocModuleConfiguration.java, fed/mosaic-cell/src/main/java/org/eclipse/mosaic/fed/cell/ambassador/CellAmbassador.java, fed/mosaic-ns3/src/main/java/org/eclipse/mosaic/fed/ns3/ambassador/Ns3Ambassador.java, fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/ambassador/SnsAmbassador.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassador.java, lib/mosaic-network/src/test/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassadorTest.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/UnitNameGenerator.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/communication/CellConfiguration.java
CellAmbassador and AbstractNetworkAmbassador now store the `Cell/AdhocCommunicationConfiguration` if no matching vehicle could be found. Those configuration interactions are again processed when a `VehicleRegistration` is received. This allows the `Cell/AdhocCommunicationConfiguration` interaction to be received BEFORE `VehicleRegistration`, which could happen with the improved Phabmacs Integration
* Internal issue 175
=> Allow CommunicationConfiguration to be received before VehicleRegistration

bundle/src/assembly/resources/fed/omnetpp/omnet_installer.sh, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/junit/MosaicSimulationRule.java
* This change allows the `omnet_installer.sh` script to download OMNeT++ automatically without the need to pass it manually. This is now possible, as the source bundles of OMNeT++ have been moved to GitHub recently.
* internal issue 226 
Yes, I updated the documentation accordingly.
=> Download OMNeT++ automatically by omnet_installer.sh script

lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/BatteryData.java
This PR only changes the way the way the `toString()` method of the `BatteryData` is build
* relates to internal issue 242
no
=> Minor improvement in BatteryData

lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/ProtobufConversion.java
* This PR adds an Interface for data-classes that are to be serialized with Protobuf
* Not certain if this is the best way to realize this
* related to internal issue 266
- [] There are no new SpotBugs warnings.
=> Add interface for data classes to be serialized with Protobuf

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Matrix3d.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Matrix4d.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/MatrixAlignment.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/RotationMatrix.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/TransformationMatrix.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/math/Matrix3dTest.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/math/Matrix4dTest.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/math/TransformationMatrixTest.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/spatial/RotationMatrixTest.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/spatial/TransformationMatrixTest.java
Signed-off-by: Karl Schrab <karl.schrab@fokus.fraunhofer.de>
* The method set of Matrix3d and Matrix4d was quite different. This PR aligns those methods to have a very similar API. 
* Both `Matrix3d` and `Matrix4d`, provide the following methods: `setIdentity`, `setZero`, `get(row, col)`, `set(row, col, value)`, `add`, `multiply`, `transpose`, `inverse`, `copy`, `isFuzzyEqual`, `equals`, `hashCode`, and `toString`
* `Matrix4d` now very generic. Everything which was related to transformation matrix has been moved to a separate class `TransformationMatrix`
* `TransformationMatrix` provides additional methods `translate`, `scale`, `rotate`, `getRotation`, `getTranslation`
* New instances of `Matrix3d` and `Matrix4d` initialize with zeros, whereas `TransformationMatrix` initializes with …
=> Cleaned up Matrix implementations and aligned method set

Jenkinsfile, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/util/TrafficLightStateDecoder.java, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
* Introduced `1.11.0` as valid SUMO version in mosaic-sumo
* Pushed new docker image for testing with SUMO 1.11.0
* Adjusted Jenkinsfile
* internal issue 276 
=> Upgrade to SUMO 1.11.0

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Matrix3d.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Matrix4d.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/MatrixElementOrder.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/RotationMatrix.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/TransformationMatrix.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/math/Matrix3dTest.java
Follow up to #161 
Renamed `MatrixAlignment` to `MatrixElementOrder` as this is a more suitable name.
=> Renamed MatrixAlignment to MatrixElementOrder

bundle/src/assembly/resources/scenarios/Barnim/output/output_config.xml, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/facades/SimulationFacade.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/BatteryData.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/Consumptions.java
This PR extends the `BatteryData`-class with additional information about energy "consumption" the BatterySimulator
was adjusted to update this information accordingly.
* relates to internal issue 254
=> Extending BatteryData by consumption information

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/VehicleUnit.java
CAMs sent with `sendCam` method always ignored the actual configured vehicle class of the vehicle.
* Resolves #171 
No
=> fix(mosaic-application): CAM ignored actual configured vehicle class

lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/DatabaseUtils.java, lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/road/Connection.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/RoutingParameters.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/GraphHopperRouting.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/TurnWeightingOptional.java
* When passing a `RoutePosition` as source or target for a routing query, the implementation first tries to match the given position onto the road, by either snapping it to a node (`Position.TOWER`) or connection (`Position.EDGE`). In some rare cases, the queried position was mapped onto a connection, although the position was very close to a node (few millimeters). To fix those cases, we now switch the snapping mode of the `QueryResult` to `Position.TOWER`, if the queried position is very close to the closest point of the matched edge. The distance to control this behavior can be adjusted with the `TARGET_NODE_QUERY_DISTANCE` field.
* Added a new method to `RoutingParameters` to define how much costs are applied for a turn restrictions. Setting this value allows to ignore …
=> fix(routing): snapping query points on node instead of edges

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/ErrorRegister.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/VehicleUnit.java
When BatteryData was generated and spread for vehicle which was not configured with `vehicleClass = ElectricVehicle`, an error message was raised which was not really helpful and required debugging to find the configuration error. This is now fixed by writing a meaningful message into the exception.
*internal issue 327 
No
=> fix(application): improved log when conventional vehicle receives battery data

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/CentralNavigationComponent.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/OriginDestinationVehicleFlowGenerator.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/VehicleFlowGenerator.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/units/COriginDestinationMatrixMapper.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/units/CVehicle.java, fed/mosaic-mapping/src/main/resources/CMappingAmbassadorScheme.json, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/config/DepartSpeedTest.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassador.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassadorTest.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/VehicleDeparture.java
Signed-off-by: Felix Lutz <felix.lutz@fokus.fraunhofer.de>
The departure connection/edge of a vehicle can now be configured via index in mapping.
Index 0 represents the first connection of a vehicle, index 1 the second connection, etc.
Resolves internal issue [324](https://gitlab.fokus.fraunhofer.de/simulation/mosaic/mosaic-extended/-/issues/324)
Mapping configuration
=> feat(mapping): Configure departure connection of vehicle

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/BoundingBox.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/QuadTree.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/spatial/QuadTreeTest.java
Signed-off-by: Karl Schrab <karl.schrab@fokus.fraunhofer.de>
Fixes the intersection test in QuadTree for checking a the search area intersects with a quad tile.
* Internal Issue 340
No
=> fix(geomath): fixed intersection test in quadtree

app/tutorials/example-applications/src/main/java/org/eclipse/mosaic/app/tutorial/cam/UserTaggedValueReadingApp.java, app/tutorials/example-applications/src/main/java/org/eclipse/mosaic/app/tutorial/cam/mapping_config.cam.json, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/ObjectInputStreamWithClassLoader.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/ObjectInputStreamWithLoader.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/SerializationUtils.java
* with this PR it is possible to call the `fromBytes(...)` method in `SerializationUtils` with an additional `ClassLoader`
* this is relevant as `SerializationUtils` uses a separate `ClassLoader` out of the box
* Relates to  [discussion 164](https://github.com/eclipse/mosaic/discussions/164)
none
=> fix(app): consider class loader during deserialization of message payload

fed/mosaic-omnetpp/src/main/java/org/eclipse/mosaic/fed/omnetpp/ambassador/OmnetppAmbassador.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassador.java, rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/time/AbstractTimeManagement.java
* Omnet++ Federate was started with a wrong path to omnetpp.ini
* AbstractNetworkAmbassasdor does not throw exception if a source node for whatever reason is not simulated anymore. This still tends to happen occasionally.
* Add timestamp to some logs in AbstractNetworkAmbassador
* The RTF shown at the end of the simulation now respects the case if the simulation was aborted. 
* Internal issue 314 
No
=> fix(omnetpp): read correct omnetpp.ini

fed/mosaic-omnetpp/src/main/java/org/eclipse/mosaic/fed/omnetpp/ambassador/OmnetppAmbassador.java
The path mounted from `OmnetppAmbassador`  did not match the path defined in the `bin/fed/omnetpp/Dockerfile`. This is fixed and the OMNeT++ federate now uses the correct `omnetpp.ini` as defined in the scenario.
* Internal issue 352
=> fix(omnetpp): use correct omnetpp.ini when starting federate with Docker

bundle/src/assembly/resources/fed/omnetpp/Dockerfile, lib/mosaic-docker/src/main/java/org/eclipse/mosaic/lib/docker/DockerRun.java, lib/mosaic-docker/src/test/java/org/eclipse/mosaic/lib/docker/DockerClientTest.java, rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/DockerFederateExecutor.java
- OMNeT++ federate's Dockerfile
- permission fix: if Docker container is not run as root, OMNeT++ has access to all relevant files
- unnecessary volume definition removed
- `omnetpp.ini` overwrite removed
- `DockerRun` extended by methods to set the Docker container's user
- `DockerRun.user(String)` - sets user explicitly
- `DockerRun.currentUser()` - sets user to current user id and group id in the form: "UID:GID" (on linux systems only)
- `DockerFederateExecutor.startLocalFederate()` calls `DockerRun.currentUser()`
* internal issue 357
No
Test of `DockerRun.currentUser()` is not implementable in an elegant way.
=> fix(omnetpp): avoid non-deletable Omnetpp result leftovers

fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/facades/SimulationFacade.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/enums/VehicleStopMode.java
* in SUMO, when a vehicle tries to leave a parking area but the "leaving lane" is occupied, it enters a state similar to being newly spawned:
* wait until lane is no longer occupied --> start driving on route
* during this state vehicles will have a invalid position, resulting in invalid `VehicleData` and the vehicle being removed from simulation
* previously we did catch this behavior in the same way as we do now, but didn't properly remove the vehicles from simulation
* with this PR we properly catch vehicles trying to leave parking areas and handle their `VehicleData` as still being parked
* Relates to internal issue 353
=> fix(sumo): do not remove vehicles which left parking areas

fed/mosaic-mapping/src/main/resources/CMappingAmbassadorScheme.json
Signed-off-by: Felix Lutz <felix.lutz@fokus.fraunhofer.de>
This PR makes it possible to set the parameter `maxSpeed` in the `mapping_config`  to zero in order to directly spawn parking vehicles. This feature only works with Phabmacs as SUMO only accepts `maxSpeed` values greater than zero.
* Link to [Eclipse Mosaic repository](https://gitlab.fokus.fraunhofer.de/simulation/mosaic/mosaic-extended/-/issues/235) issue
Yes
=> feat(mapping): possibility to set maxSpeed to zero

fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/reader/TrafficLightProgramTraciReader.java, fed/mosaic-sumo/src/test/resources/sumo-test-scenario/scenario.net.xml
- in this [discussion#220](https://github.com/eclipse/mosaic/discussions/220) an issue came up where the simulation wasn't running when adding params to tl-logics
- in `TrafficLightProgramTraciReader` we do read this parameters, however don't add the read bytes to the parent-command,
which lead to the simulation getting stuck, as the TraCI-coupling tried reading more bytes
* Related to this [discussion#220](https://github.com/eclipse/mosaic/discussions/220)
none
=> fix(sumo): properly read tl logic params

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SimplePerceptionModule.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SimplePerceptionModuleTest.java
* This PR enables the perception module to use full 360° surround perception
* This is done by extending the methodology applied in the first place by using the dot-product of vectors
* However, the dot-product only works for viewing angles less than 180°, so instead of comparing the left- and right-bound vectors, we do two checks:
* 1st check if point is right of leftBound and left of headingVector
* or 2nd check if point is left of rightBound and right of headingVector
* the image describes the process
* additionally we explicitly include points lying on the edges of the viewing range, which wasn't the case before due to floating point inaccuracies
The perception module documentation should already be up to date
=> feat(application): enable full 360 degree perception range

lib/mosaic-docker/src/main/java/org/eclipse/mosaic/lib/docker/DockerRun.java, lib/mosaic-docker/src/test/java/org/eclipse/mosaic/lib/docker/DockerClientTest.java
- `com.sun.security.auth.module.UnixSystem` is not available on Windows
- bypass import of that class on non-Unix systems
* Link to [Eclipse Mosaic repository](https://github.com/eclipse/mosaic/issues) issue
=> fix(docker): bypass import of UnixSystem class if not available in jdk

bundle/src/assembly/resources/fed/ns3/Dockerfile
- permission fix for the case: ns3 container is not run as root
- By default the container is run as the current user (-> pull requests #227 and #228). This enables MOSAIC to delete temporary folders.
* internal issue 365
non
=> fix(ns3): set permission for execution as non-root user

rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/DockerFederateExecutor.java, rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java
- parallel execution of federates based on same Docker image was not possible due to simulation independent container names
- new private properties introduced to class `MosaicSimulation`:
- `scenarioId`: for example `Barnim`
- `simulationId`: for example `20220630-151732-Barnim`
- a Docker federate's container name is set to `MosaicSimulation.simulationId`
* internal issue 375
none
=> fix(docker): support parallel execution of docker federates

bundle/src/assembly/resources/scenarios/Tiergarten/omnetpp/omnetpp.ini
- `omnetpp.ini` changed
- less verbose logging
* internal issue 376
no
=> fix(omnetpp): less verbose logging

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/facades/SimulationFacade.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/bridge/TraciTest.java, pom.xml, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
Upgrades Code and CI to use new SUMO release 1.14.0. With the new version, fuel consumption is returned in mg instead of ml, thus the returned value is converted back to ml assuming a density of 0.74 g/cm³ (see https://kraftstoff-info.de/vergleich-der-kraftstoffe-nach-energiegehalt-und-dichte).
* Internal issue 392 
* Yes, will be fixed with the new release of MOSAIC.
=> feat(sumo): upgrade to SUMO 1.14.0

bundle/src/assembly/resources/scenarios/Tiergarten/omnetpp/omnetpp.ini
- revised omnetpp.ini:
- no mobility section
- log prefix extended by unit for simulation time
- mac/phy layer settings revised
* internal issue 381
none
=> fix(omnetpp): revised omnetpp.ini

rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java
- rename: `MosaicSimulation.scenarioId` -> `MosaicSimulation.federationId`
- removal of unnecessary local variable `simId` in `MosaicSimulation.createFederation()`
* internal issue 384
=> fix(rti): clarification of usage of federationId and simulationId

fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/MappingAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/util/MosaicConformVehicleIdTransformer.java
A `VehicleRegistration` is now only send for those `ScenarioVehicleRegistration`, which match prototype **and** weight condition. In previous versions a `VehicleRegistration` was send with an empty list of applications, if the weight condition was not met, resulting in unnecessary and misleading `VehicleRegistration` interactions.
* Internal issue 403
No.
=> fix(mapping): send VehicleRegistration only for equipped scenario-generated vehicles

fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassador.java
* This PR allows MOSAIC to start SUMO without the need of a `VehicleRoutesInitialization`-interaction
* to achieve this minor changes in the logic of the `SumoAmbassador` were necessary
* relates to internal issue 404
No documentation is affected
=> feat(sumo): Start SUMO without the need of VehicleRoutesInitialization

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/transform/GeoProjection.java
Previously, `GeoProjection.getGeoCalculator()` could throw an `IllegalStateException` when executed in a multi-threaded environment and geo-calculator has not been initialized before. This PR fixes that by making the check if geo-calculator is initialized thread safe.
none
none
none
=> fix(geomath): thread-safe initialization of geoCalculator

bundle/src/assembly/resources/fed/ns3/Dockerfile, bundle/src/assembly/resources/fed/ns3/ns3_installer.sh
- ns-3 version increased from 3.34 to 3.36.1
- `Dockerfile`: installation of package `cmake`
- depends on changes of `premake5.lua` in federate repository
* internal issue 459
* https://github.com/mosaic-addons/ns3-federate/pull/8
- https://www.eclipse.org/mosaic/docs/simulators/network_simulator_ns3/
- table: version
- Installation -> Minimum Requirements: cmake
=> feat(ns3): upgrade to ns-3 3.36.1

fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/ambassador/OutputAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/AbstractSumoAmbassador.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassadorTest.java, rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/AbstractFederateAmbassador.java, rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/parameters/FederateDescriptor.java, rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/parameters/FederatePriority.java, rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/time/FederateEvent.java, rti/mosaic-rti-api/src/test/java/org/eclipse/mosaic/rti/api/parameters/FederatePriorityTest.java, rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/MosaicRtiAmbassador.java, rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java, rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/config/CScenario.java
* Changes the handling of priorities when processing time advance requests. When ordering `FederateEvents`, the `priority` field was considered in descending order, meaning, that with two events with same time but different priority, the event with the _higher_ priority values was processed first. However, in the `runtime.json` the priority configuration was defined differently, with having lower values for higher priorities. 
* Therefore, this change inverts the ordering of `FederateEvents` with equal timestamps, by processing events with _lower_  priority values first:
* Changed the ordering in `FederateEvent.compareTo` to process time advance requests with lower priority values first. The actual comparison was moved to `FederatePriority`.
* When `receiveInteraction()` is called on an …
=> refactor(rti): changes the handling of priorities when processing time advance requests

bundle/src/assembly/resources/scenarios/Barnim/output/output_config.xml, bundle/src/assembly/resources/scenarios/HelloWorld/output/output_config.xml, bundle/src/assembly/resources/scenarios/Tiergarten/output/output_config.xml, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/ambassador/AbstractOutputGenerator.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/ambassador/ConfigHelper.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/ambassador/RegistrationSubscriptionTypes.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/FileOutput.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/FileOutputLoader.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/filter/EqualsFilter.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/filter/Filter.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/filter/FilterFactory.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/filter/MaxFilter.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/filter/MinFilter.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/filter/RegexFilter.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/format/ExtendedMethodSet.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/format/InteractionFormatter.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/format/MethodElement.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/format/MethodManager.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/write/Write.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/write/WriteByFile.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/write/WriteByFileCompress.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/write/WriteByLog.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/websocket/WebsocketVisualizer.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/websocket/WebsocketVisualizerLoader.java, fed/mosaic-output/src/main/resources/output_config.xsd, fed/mosaic-output/src/test/java/org/eclipse/mosaic/fed/output/generator/file/format/InteractionFormatterTest.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/InteractionUtils.java
* with this PR the decimal separator for output CSV's can now be configured in the `output_config.xml`'s
* this was realized using `DecimalFormat` which also makes output more consistent over different systems
* some cleanup
* solves internal issue 454
This enhancement needs to be documented on the website https://www.eclipse.org/mosaic/docs/visualization/filevis/
=> feat(output): Decimal Separator is now configurable

README.md
* Fixes logo appearance in dark mode. Previously, both dark and light mode logo were visible in dark-mode. This is now fixed by appending `#gh-dark-mode-only` to the `src` field in the image tag.
=> fix(readme): fixed visibility of light mode logo

README.md, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/PerceptionModifierTest.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SimplePerceptionModuleTest.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/junit/SumoTraciRule.java, pom.xml
This PR allows Eclipse MOSAIC to be build using JDK 17. The following changes needed to be applied:
* Upgraded `mockito-core` to `3.12.4`. We do not need to check with Eclipse IP here since we do not ship mockito with our bundle.
* With the mockito upgrade, mocks annotated with `@Mock` are initialized later and could not be used in `@Rule` annotated object initializations. The required mocks are now initialized using `mock(MyClass.class)` instead.
* Fixed a bug in `SumoTraciRule` which would keep sumo processes alive if an initial connection has failed. 
Internal issue 468
Yes, table with supported versions will be adjusted with next release.
=> feat: added support for compilation with JDK 17

Jenkinsfile, bundle/src/assembly/resources/scenarios/Highway/sumo/highway.add.xml, bundle/src/assembly/resources/scenarios/Sievekingplatz/sumo/sievekingplatz.bus.add.xml, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/AbstractSumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/config/CSumo.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/bridge/TraciTest.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/junit/SumoTraciRule.java, fed/mosaic-sumo/src/test/resources/density-flow-scenario/density_flow.detector.xml, fed/mosaic-sumo/src/test/resources/density-flow-scenario/density_flow.rou.xml, fed/mosaic-sumo/src/test/resources/sumo-test-scenario/parking.add.xml, fed/mosaic-sumo/src/test/resources/sumo-test-scenario/scenario.detector.xml, fed/mosaic-sumo/src/test/resources/sumo-test-scenario/scenario.rou.xml, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/ProcessLoggingThread.java, pom.xml, rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/federation/LocalFederationManagement.java, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/ReleaseHelloWorldIT.java, test/scenarios/perception-module/sumo/square.rou.xml, test/scenarios/sumo-predefined-scenario-integration/sumo/tiergarten.rou.xml
Upgrades to support SUMO 1.15.0
SUMO 1.15.0 disabled XSD lookup if SUMO_HOME is not set. This results in failing validation during startup. To overcome this, we disable validation completely if SUMO_HOME is not set, by passing the parameter `--xml-validation never`. If SUMO_HOME is set, we keep the default behavior.
During debugging I already adjusted some XML files to be validated successfully. This is not really required, by we may keep this now.
Offtopic change:
* simplified/generalized use of ProcessLoggingThread 
Internal issue 491
We could update website on next release
=> feat(sumo): upgrade to SUMO 1.15.0

bundle/src/assembly/resources/scenarios/Barnim/mapping/mapping_config.json, bundle/src/assembly/resources/scenarios/HelloWorld/mapping/mapping_config.json, bundle/src/assembly/resources/scenarios/Highway/mapping/mapping_config.json, bundle/src/assembly/resources/scenarios/Sievekingplatz/mapping/mapping_config.json, bundle/src/assembly/resources/scenarios/Tiergarten/mapping/mapping_config.json, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/CMappingConfiguration.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/units/COriginDestinationMatrixMapper.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/units/CVehicle.java, fed/mosaic-mapping/src/main/resources/CMappingAmbassadorScheme.json, fed/mosaic-mapping/src/test/resources/mapping/Tiergarten.json, fed/mosaic-mapping/src/test/resources/mapping_config_scale.json, fed/mosaic-mapping/src/test/resources/mapping_config_weights_in_prototype.json, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/gson/TimeFieldAdapter.java
* Integrated proposed `DoubleTimeFieldAdapter`s
* `startingTime`s, `endTime`s use these adapters 
* all bundled scenarios will now use starting time definitions in the form of "x.x s"
* additionally some occurrences in test mapping-configs now use a string definition
relates to internal issue 421
Yes see internal website MR 67
=> feat(mapping): Integrate DoubleTimeFieldAdapters

rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/time/ScheduledEvents.java
Multi-threaded time management tried to read and manipulate the lookahead queue in `ScheduledEvents` simultaneously. Occasionally, this could lead to NPE when `getMaximumValidTime()` tried to read the peek value of the lookahead queue but could request an empty queue when `ThreadWorker` removed the latest lookahead value from the queue in the mean time.
This PR includes a further synchronized block to avoid concurrent access on the lookahead queue. ThreadWorker already uses `isEmptyMutex` when removing the latest lookahead value; this mutex is now also used in `getMaximumValidTime()`.
Internal issue 519 
No
=> fix(rti): resolved racing condition in RTI

fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/SpawningFramework.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/util/MosaicConformVehicleIdTransformer.java
* The following warning has been moved from the root-logger to the `SpawningFramework`-logger and can now be found in the `mapping.log`
* additionally, the level has been changed to "INFO" as this behavior is most likely intentional
* also the log message has been adjusted for better clarity
```
WARN  ROOT - You didn't define any spawners in your mapping config. Only external vehicles will be simulated.
```
* When simulating external scenarios the assigned MOSAIC vehicle ID's where only retraceable when log-level `DEBUG` was set, however this information is often relevant and has been moved to `INFO`
* this change is made in `MosaicConformIdTransformer`
* furthermore, the message has been adjusted for better clarity
relates to internal issue 523
None
=> cleanup(logging): Improved Logging related to simulation of external scenarios

fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/SpawningFramework.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/VehicleFlowGenerator.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/ChargingStationSpawner.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/RoadSideUnitSpawner.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/ServerSpawner.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/TrafficManagementCenterSpawner.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/UnitSpawner.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/VehicleTypeSpawner.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/flow/ConstantSpawningMode.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/flow/GrowAndShrinkSpawningMode.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/flow/PoissonSpawningMode.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/units/CChargingStation.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/units/CServer.java, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/VehicleTypeSpawnerTest.java
* This PR integrates minor improvements to the logging in the Mapping federate
* the `departureConnectionIndex` is now named `departConnectionIndex` and is properly separated with an "="
* prior to this apps were printed twice (once for the type and then again separately) -> this is now only logged once
Example of improved logging:
previous:
```
INFO  VehicleFlowGenerator - Creating Vehicle. time=5000000000, name=veh_3, route=1, laneSelectionMode=DEFAULT, lane=0, departureConnectionIndex0, pos=1417, type=Vehicle: name=Car, apps=org.eclipse.mosaic.app.tutorial.WeatherWarningAppCell,org.eclipse.mosaic.app.tutorial.SlowDownApp, departSpeed=0.0, apps=[org.eclipse.mosaic.app.tutorial.WeatherWarningAppCell, org.eclipse.mosaic.app.tutorial.SlowDownApp]
```
now:
```
INFO  VehicleFlowGenerator - …
```
=> cleanup(mapping): cleaned up some logging in mapping

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassador.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/CentralPerceptionComponent.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SumoPerceptionModule.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/TrafficObjectIndex.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/objects/VehicleObject.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/SumoIndex.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/TrafficLightIndex.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/TrafficLightMap.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/TrafficLightTree.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/VehicleGrid.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/VehicleIndex.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/VehicleMap.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/VehicleTree.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/PerceptionModifierTest.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SimplePerceptionModuleTest.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/MappingAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassador.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/AbstractPerceptionModuleIT.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/PerceptionModuleSumoIndexIT.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/perceptionmodule/SimplePerceptionApp.java, test/scenarios/perception-module/mapping/mapping_config.json, test/scenarios/perception-module/sumo/square.net.xml, test/scenarios/perception-module/sumo/square.rou.xml, test/scenarios/perception-module/sumo/square.sumocfg
* With the integration of vehicle dimensions (i.e., length, width, height) #278 in the `VehicleObject`s the `CentralPerceptionComponent` required `VehicleRegistration`s to extract the dimensions
* This broke the ability for all vehicles to be handled in the perception index -> vehicles failing the `weight` condition in the `MappingAmbassador`
* With this PR this functionality was revived
* Additionally, all `VehicleType`s configured in the *mapping_config.json* are now held in the `vehicleTypes`-map in the `SimulationKernel`, which enables type retrieval when adding vehicles to the perception index
* vehicles with no configured prototype will have (0, 0, 0) as their dimensions
* the perception integration test has been extended to better look at edge cases
* future work may improve on …
=> fix(perception): Re-enable the perception of unequipped vehicles

fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/AbstractSumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/LibSumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoGuiAmbassador.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/junit/LibsumoCheckRule.java
Since 1.16.0, the `libsumojni.dll` cannot be loaded anymore, resulting in a `UnsatisfiedLinkError` due to a missing dependent library. According to https://github.com/eclipse/sumo/issues/12605, neither the reason nor a solution for the error could be found, however, a workaround is proposed by loading dependent libraries before loading `libsumojni.dll`.
This MR implements the workaround by loading `iconv-2.dll`, `intl-8.dll` and `proj_9_0.dll` in advance. This is only executed on Windows machines, as it ~~seems to~~ works on Linux based systems as usual.
* Internal issue 559
**Required**
=> fix(sumo): workaround for loading libsumojni dll on Windows

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/AbstractPerceptionModule.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/objects/SpatialObject.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/objects/TrafficLightObject.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/objects/VehicleObject.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/PerceptionModifierTest.java
* When perception modifiers were configured, they changed not only the perceived traffic objects, but also the indexed objects.
* This would lead to problems as soon as two vehicles with perception modifiers would perceive the same object.
* Therefore, with this PR copies of all `SpatialObject`s are created, before passing them to the configured perception modifiers. This is only done if perception modifiers are configured, in order to avoid unnecessary copy operations if they would not be required.
* An additional unit test proofs that the objects in the index are still at their original positions after applying any modifiers.
* Resolves issue internal issue 564
No
**Required**
=> fix(perception): perception modifiers should not alter objects from the index

app/tutorials/example-applications/src/main/java/org/eclipse/mosaic/app/tutorial/vehicle/PerceptionApp.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/AbstractPerceptionModule.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SimplePerceptionConfiguration.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/PerceptionModifierTest.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SimplePerceptionModuleTest.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/api/VehicleGetTeleportingList.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/facades/SimulationFacade.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/libsumo/VehicleGetTeleportingList.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/VehicleGetTeleportingList.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/VehicleSubscribe.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/constants/CommandRetrieveVehicleState.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/reader/VehicleSubscriptionTraciReader.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/SumoTeleportIT.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/perceptionmodule/SimplePerceptionApp.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sendonshutdown/SendOnShutdownApp.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sendonshutdown/ServerReceiverApp.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sumoteleport/TeleportingVehicleApp.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/junit/MosaicSimulationRule.java, test/scenarios/sumo-predefined-scenario-integration/mapping/teleport_mapping_config.json, test/scenarios/sumo-predefined-scenario-integration/sumo/teleport_sumo_config.json, test/scenarios/sumo-predefined-scenario-integration/sumo/teleport_tiergarten.rou.xml, test/scenarios/sumo-predefined-scenario-integration/sumo/teleport_tiergarten.sumocfg
* This PR adds proper handling of SUMO vehicles that teleport for more than one second
* Instead of removing them from the subscription list they will now have the `VehicleData` from the last time step before the teleport starts.
* To differentiate between parking/stopped vehicles the `VehicleStopMode` will be set to `NOT_STOPPED`.
* The current implementation requires the additional traci command `getTeleportingList` of the vehicle domain. However, the calls are limited as they are only required if the subscription result from SUMO was erroneous.
* The new functionality is tested by an integration test, which builds on the existing Tiergarten test-scenario.
* As an additional feature of this PR the instantiation of the `SimplePerceptionConfiguration` has been transferred to be using a …
=> bugfix(sumo): Proper handling of teleporting vehicles

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassador.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/AbstractSimulationUnit.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/util/EventNicenessPriorityRegister.java
* it was found that if an application schedules an event at the time of shutdown, the event could triggered after the application was already teared down
* to prevent this the niceness value `UNIT_REMOVED` was introduced, which schedules shutdown events with a low priority
* additionally the names of the constants in `EventNicenessPriorityRegister` were adjusted according to style conventions
* the log-levels of the OS-check in `AbstractSimulationUnit` were moved from `WARN` to `DEBUG` as this check fails when we introduce more complex application-class hierarchies 
* None
**Required**
=> fix(application): schedule application shutdown events last

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/SimulationKernel.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/util/UnitLogger.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/util/UnitLoggerImpl.java
Adds convenient functions for applications to obtain the log directory of the unit (`getLog().getUnitLogDirectory()`) or the log directory of the simulation (`SimulationKernel.SimulationKernel.getMainLogDirectory()`), in order to place CSV or other files in the log directories.
Replaces several code duplications in the extended codebase.
* Part of internal issue 604
**Required**
=> feat: provide logger directory for applications

fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/libsumo/SimulationSimulateStep.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/reader/StoppingPlaceReader.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/database/DatabaseRouting.java
* rearranged some code and added some comments in SUMO bridge parts to show that the start position is missing in traci coupling
* relates to issue 625
* no changes required
**Required**
=> cleanup(general): Renamed variable in DatabaseRouting

fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/AbstractSumoAmbassador.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassadorTest.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassadorTimeStepAdjustmentTest.java
* this PR reverts a regression that happened during a refactor and would lead to the issue described in #326
* it was fixed by calling `adjustToSumoTimeStep` with the configured update interval as nanoseconds instead of milliseconds (i.e., `sumoConfig.updateInterval * TIME.MILLI_SECOND`)
* solves internal issue 629
* Resolves issue #<eclipse-mosaic-issue> / internal issue <internal-issue>
* no changes required
**Required**
=> bugfix(sumo): Fix call of adjustToSumoTimeStep

lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/gson/PackageSpecificTypeAdapter.java
In order to allow the `PackageSpecificTypeAdapter` also work within context of applications, the correct class loader must be specified. This is now possible with this given change. The application code which uses this type adapter must now pass the `SimulationKernel.SimulationKernel.getClassLoader()` to this type adapter.
* Resolves issue internal issue 620
**Required**
=> f:ix allow to set a classloader for PackageSpecificTypeAdapter

fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/VehicleTypeSpawner.java, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/VehicleTypeSpawnerTest.java
When `decel` was configured in the `types` section of either a `vehicle` or `matrixMapper`, it was missed when the corresponding ` VehicleType` was created. See discussion #336 .
This is now fixed and a test has been added to check all currently existing fields
* Resolves issue #336 
No
**Required**
=> fix(mapping): decel was missed when creating a vehicle type

.github/workflows/maven.yml, Jenkinsfile, README.md, pom.xml, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
Due to the increase of components which are compiled with JDK version 11, we finally take the step and migrate to Java 11, too. Since we were already compatible to Java 11 during runtime, no code had to be adjusted. From now on, we furthermore can take advantage of new Java 11 features, such as `var` keyword for local variables or additional `String` methods.
* Resolves internal issue 640
There are many parts in our online documentation which need to be adjusted with the next release.
**Required**
=> feat: use Java 11 as compiler target

bundle/src/assembly/resources/scenarios/Barnim/mapping/mapping_config.json, bundle/src/assembly/resources/scenarios/HelloWorld/mapping/mapping_config.json, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/MappingAmbassador.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/OriginDestinationVehicleFlowGenerator.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/SpawningFramework.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/VehicleFlowGenerator.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/weighting/FixedOrderSelector.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/CMappingConfiguration.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/units/CVehicle.java, fed/mosaic-mapping/src/main/resources/CMappingAmbassadorScheme.json, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/ambassador/MappingAmbassadorTest.java, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/ambassador/weighting/FixedOrderSelectorTest.java, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/config/BarnimMappingTest.java, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/config/TiergartenMappingTest.java, fed/mosaic-mapping/src/test/resources/mapping/invalid/matrixMapper/point/MissingProperties.json, fed/mosaic-mapping/src/test/resources/mapping/invalid/matrixMapper/point/position/MissingProperties.json, fed/mosaic-mapping/src/test/resources/mapping/invalid/matrixMapper/point/position/center/MissingProperties.json, fed/mosaic-mapping/src/test/resources/mapping_config_reference.json, fed/mosaic-mapping/src/test/resources/mapping_config_weights_in_prototype.json
* Instead of configuring `fixedOrder` for every vehicles spawner, it can now be configured once in the common configuration section of the `mapping_config.json`
* This also allows to consider this config when transforming `ScenarioVehicleRegistration` to `VehicleRegistration`
* Resolves internal issue 678
Yes, separate MR is created.
**Required**
=> feat: configure fixedOrder globally instead for every spawner

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/objects/SpatialObject.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/objects/SpatialObjectAdapter.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/objects/VehicleObject.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SimplePerceptionModuleTest.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/Grid.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/QuadTree.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/SpatialItemAdapter.java
* When storing `VehicleObject` items in the `Grid` or `QuadTree`, they were stored as a key within a HashMap. When doing so, the hashCode of the object is used to store it in the map. However, when updating the object (e.g. adjusting its speed value), the object cannot be found anymore since its hashCode has changed and differs from the one stored in the map. This resulted in odd behavior and `VehicleObject`s could not be removed from the `Grid` or `QuadTree` and were therefore returned by the perception module,
* With this PR the behavior is fixed. Now, internal maps in `Grid` and `QuadTree` do not store the `VehicleObject` items as a key for HashMaps, but only their hash value. This hash value is furthermore generated by the `SpatialItemAdapter`. The adapter implementation responsible …
=> fix: remove items from index implementations grid and tree (regression)

fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/writer/StringTraciWriter.java
This PR fixes a bug in the `StringTraciWriter` class which failed to send a string if it contained at least one UTF-8 character which is represented by more than one byte. To support all characters of the UTF-8 standard, which include characters of Arabic, Chinese, Hebrew, Japanese, Turkish, but also emoji characters, a simple fix in `StringTraciWriter` has been made, which now sends the length of the encoded byte array rather than the number of characters in the String via TraCI.
**Required**
=> fix(sumo): allow all utf-8 characters via traci

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/TraciVersion.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/VehicleAdd.java, test/ci/ci-image-mvn-sumo/Dockerfile
* Adds support for SUMO 1.19.0
* TraCI API version has been raised. No technical changes required, except adding `API_21` enum value.
* Resolves internal issue 723
**Required**
=> feat(sumo): support for sumo 1.19.0

legal/templates/license-header-2024.txt, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/VehicleReferenceUtils.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/VehicleUtils.java, pom.xml, rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicStarter.java
* Simulators may have different reference positions of vehicles, e.g. SUMO points on center of front bumper, while Carla and PHABMACS refer to the center of the vehicle's bounding box.
* A later goal should be to generalize this across MOSAIC, so simulators may have to adjust the positions they put into `VehicleData` objects.
* As a first step, this MR provides utility functions to conveniently convert from "front bumper" to "bb center" and vice versa for the 2D-case.
* Resolves internal issue 767
Not yet
**Required**
=> feat(utils): add utility function to move vehicle reference position

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassador.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/SimulationKernel.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/CentralNavigationComponent.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/INavigationModule.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/IRoutingModule.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/NavigationModule.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassadorTest.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/navigation/CentralNavigationComponentTest.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/navigation/NavigationModuleTest.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/SumoAmbassador.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Aggregator.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/VehicleDeparture.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/database/DatabaseRouting.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/GraphHopperRouting.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/scheduling/Event.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/mosaicandsumovehicles/SumoVehicle.java
Various minor improvements/fixes required by recent applications related to ride-hailing.
* Routes have been stored twice in `SimulationKernel` and `CentralNavigationComponent`, but have been updated only in `SimulationKernel`. This leads to buggy behavior when working with routes in applications. Now, routes are stored and updated only in `SimulationKernel`.
* Applications can now request information about connections. This was done by adding `getConnection(id)` to `INavigationModule`.
* When a vehicle type is not used by any spawner in `mapping_config.json`, it is not propagated to `mosaic-sumo`, thus it is unknown and results in an NPE when processing a `VehicleRegistration` interaction with a vehicle type not configured in mapping. Now you may ask: "how can a VehicleRegistration …
=> feat: various changes required for ride-hailing 

app/tutorials/traffic-light-communication/src/main/java/org/eclipse/mosaic/app/tutorial/message/GreenWaveMsg.java, app/tutorials/traffic-light-communication/src/main/java/org/eclipse/mosaic/app/tutorial/message/InterVehicleMsg.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/VehicleTest.java, fed/mosaic-cell/src/main/java/org/eclipse/mosaic/fed/cell/utility/CapacityUtility.java, fed/mosaic-cell/src/test/java/org/eclipse/mosaic/fed/cell/chain/SampleV2xMessage.java, fed/mosaic-sns/src/test/java/org/eclipse/mosaic/fed/sns/ambassador/SnsAmbassadorTest.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassador.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/GenericV2xMessage.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/V2xMessage.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/Cam.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/Denm.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/Ivim.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/Spatm.java, lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/v2x/etsi/CamContentTest.java, lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/v2x/etsi/DenmContentTest.java, lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/v2x/etsi/IvimContentTest.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sendandreceive/messages/TestMessage.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/app/sendonshutdown/ShutdownMessage.java
* This PR introduces an API change to correct spelling
* the method `V2xMessage#getPayLoad` is now correctly spelled as `V2xMessage#getPayload`
* all occurrences using this API were adjusted accordingly
BREAKING CHANGE: Applications using the `V2xMessage#getPayLoad()`-method will have to adjust to the corrected spelling of `V2xMessage#getPayload()`
* Resolves internal issue 771
- None, if I checked properly
**Required**
=> fix(v2x): API Change in V2xMessage getPayLoad -> getPayload

bundle/src/assembly/resources/scenarios/Barnim/cell/cell_config.json, bundle/src/assembly/resources/scenarios/Tiergarten/cell/cell_config.json, fed/mosaic-cell/src/main/java/org/eclipse/mosaic/fed/cell/config/CCell.java, fed/mosaic-cell/src/main/java/org/eclipse/mosaic/fed/cell/module/streammodules/StreamModulesDebugLogger.java, fed/mosaic-cell/src/main/java/org/eclipse/mosaic/fed/cell/module/streammodules/StreamProcessor.java, fed/mosaic-cell/src/main/java/org/eclipse/mosaic/fed/cell/utility/CapacityUtility.java, fed/mosaic-cell/src/test/java/org/eclipse/mosaic/fed/cell/junit/CellConfigurationRule.java, fed/mosaic-cell/src/test/java/org/eclipse/mosaic/fed/cell/module/DownstreamModuleTest.java, fed/mosaic-cell/src/test/java/org/eclipse/mosaic/fed/cell/module/UpstreamModuleTest.java, fed/mosaic-cell/src/test/resources/logback-test.xml, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/gson/DataFieldAdapter.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/CellSnsCamSendAndReceiveIT.java, test/scenarios/cell-sns-cam-send-and-receive/cell/cell_config.json
Introduces a simplified modelling of headers added to payload of messages sent trough the cellular stack.
* Adding a 20-byte sized TCP or 8-byte sized UDP header to each message, according to its transport mode.
* Always adding a 20-byte sized IP header to each message.
* When adding the message to the cellular part of the network (e.g. sent from a vehicle), additional bytes are added to represent the headers of the cellular stack. Since the actual cellular stack may change and depend on the simulation scenario, we named it `cellularHeader` (and is configurable). In the default case, we assume an LTE stack adding another 26 bytes to each message (PDCP (6 bytes) + RLC (4 bytes) + MAC (10 bytes) + PHY (6 bytes) ).
* When the receiver or sender is a server, it is assumed that it is connected …
=> feat(cell): model header sizes for messages transmitted by cell

lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/DuplicatableMessage.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/DuplicatableMessage.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/GenericV2xMessage.java
- introducing "DuplicatableMessage" interface for V2xMessage inheritors
- allows duplicating a specialised V2XMessage without importing it 
- used by `VariableRetransmissionApp.java` when retransmitting a message 
* Resolves issue: internal issue mosaic-extended#834
none
**Required**
- more code changes in mosaic-extended (same branch name)
=> introduced duplicatable V2XMessage functionality

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/LibSumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, pom.xml, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
* Adds support for SUMO 1.20.0
* Updated version in README
* SUMO 1.20.0 libsumojni.jar is not yet available, therefore currently only upgrade `LibSumoAmbassador` to 1.19.0, but tested already with 1.20.0-SNAPSHOT.
Yes, but only on next MOSAIC release.
**Required**
=> feat(sumo): support for SUMO 1.20.0

checkstyle.xml, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/AbstractSimulationUnit.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/LibSumoBridge.java, lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/persistence/SQLiteWriter.java, lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/spatial/Edge.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Vector3d.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/AStar.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/BoundingBox.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/KdTree.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/LineString.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/spatial/QuickHull2d.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/transform/LazyGeoProjection.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/transform/Wgs84Projection.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/ClientServerChannel.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/addressing/IpResolver.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/ClassUtils.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/VehicleReferenceUtils.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/cli/CommandLineParser.java, pom.xml, rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/RtiAmbassador.java, rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/time/SequentialTimeManagement.java, rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java, rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicStarter.java
* done to support intelliJ checkstyle plugin
* some adjustments in the configuration were required due to version changes
* Resolves issue internal issue 845
**Required**
=> chore(checkstyle): bumped checkstyle version to 10.15.0

fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/ambassador/OutputAmbassador.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/ambassador/OutputGeneratorLoader.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/FileOutputLoader.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/websocket/WebsocketVisualizerLoader.java
In order to enable license check for output generators in MOSAIC Extended, we need to pass the RTI to the `OutputGeneratorLoader`.
* Part of internal issue 860
**Required**
=> feat(output): pass RTI to output generators for additional interaction

rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/federatestarter/JavaFederateExecutor.java, rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/WatchDogThread.java, rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java
* This extends the JavaFederateExecutor to be able to pass JVM options.
* Furthermore, the RTI initialization now creates the `ComponentProvider` _before_ building the `FederateExecutors`.
* Part of internal issue 861
No
**Required**
=> feat(rti): pass JVM options to JAVA based federates

bundle/src/assembly/resources/scenarios/Barnim/output/output_config.xml, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/format/ExtendedMethodSet.java
It is now possible to print details of the `V2xMessage` via file output for `V2xMessageReception` interactions:
```xml
<subscription id="V2xMessageTransmission"/>
<subscription id="V2xMessageReception">
<entries>
<entry>Time</entry>
<entry>Type</entry>
<entry>Message.Payload.EffectiveLength</entry>
<entry>ReceiverName</entry>
</entries>
</subscription>
```
Documentation will be extended.
**Required**
=> feat(file-output): add Message as an extended method for V2xMessageReception

fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/ambassador/OutputGeneratorLoader.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/file/FileOutputLoader.java, fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/generator/websocket/WebsocketVisualizerLoader.java, fed/mosaic-output/src/test/java/org/eclipse/mosaic/fed/output/ambassador/TestOutputGeneratorLoader.java
* Previously, implementations of `OutputGenerator` had to override the `initialize` method and were required to call `super.initialize`, which is a anti-pattern to avoid. 
* This MR marks `initialize` as a `final` method and defines an additional abstract `configure` method which all subclasses need to implement to read additional parameters from the output generator configuration.
* Resolves internal issue 875
No
**Required**
=> refactor(output): cleaner initialization of output generators

app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherServerApp.java, app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherWarningApp.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/AbstractSimulationUnit.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/ServerUnit.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/ReleaseBarnimIT.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/ReleaseBarnimLibsumoIT.java
The all-knowing weather server sends out warnings from second one. So any cell device will omit the icy region from the beginning on, and not a single cell-car will go towards the icy region.
I think it's more realistic, that the server can just relay the warnings that it received by cars.
For simplicity of the tutorial, the server will just memorize the last warning, and relay this last warning, independent from which car and from where it was sent.
* Resolves internal issue 887
**Required**
=> feat(tutorial): WeatherServerApp now relays the last received DENM

app/tutorials/traffic-light-communication/src/main/java/org/eclipse/mosaic/app/tutorial/EventSendingApp.java, app/tutorials/traffic-light-communication/src/main/java/org/eclipse/mosaic/app/tutorial/MessageReceivingApp.java, app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherWarningApp.java, bundle/src/assembly/resources/scenarios/Tiergarten/mapping/mapping_config.json, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/navigation/NavigationModule.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/VehicleRoute.java
Small fixes that arose when getting familiar with MOSAIC
* Resolves internal issue 885
**Required**
=> fix(tutorial): tiny improvements on weather warning application

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/LibSumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, pom.xml, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
* Adds SUMO 1.21.0 to supported versions of SUMO
* Configure CI to use 1.21.0 for all tests (elipse CI)
* 
* Resolves internal issue 913
README adjusted. Website will be adjusted with the next release of MOSAIC
**Required**
=> feat(sumo): support sumo 1.21.0

fed/mosaic-ns3/src/main/java/org/eclipse/mosaic/fed/ns3/ambassador/Ns3Ambassador.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassador.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/ClientServerChannel.java
Enable to start ns3 from windows-mosaic
* Resolves internal issue 894
Changes in the documentation required? yes, PR exists
**Required**
=> feat: run windows-mosaic with wsl-ns3

fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/ambassador/TransmissionSimulator.java, fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/model/AdhocTransmissionModel.java, fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/model/SimpleAdhocTransmissionModel.java, fed/mosaic-sns/src/main/java/org/eclipse/mosaic/fed/sns/model/SophisticatedAdhocTransmissionModel.java, fed/mosaic-sns/src/test/java/org/eclipse/mosaic/fed/sns/model/AdhocTransmissionModelTest.java
SNS covers already various addressing/routing modes. With this MR, multihop unicast for both topoligic or geographic routing are added by re-using existing methods. Multi-hop Broadcast is still missing.
|Addressing|Routing|Support|
|--|--|--|
|Unicast|Topologic|✅Singlehop<br>✅**Multihop (new)**|
|Broadcast|Topologic|✅Singlehop<br>❌Multihop|
||||
|Unicast|Geographic|✅**Singlehop (new)**<br>✅**Multihop (new)**|
|Broadcast|Geographic|✅Singlehop<br>✅Multihop|
The `SimpleAdHocTransmissionModel` does not really count hops between single vehicles, but instead uses a configured multi-hop delay which is applied as soon as more than hop is required.
The `SophisticatedAdHocTransmissionModel` uses existing method `forward` (which was initially used by the Geographic routing) to send the message to a …
=> feat(sns): support multi-hop unicast for topological and geographical routing

app/tutorials/example-applications/src/main/java/org/eclipse/mosaic/app/examples/commuter/SimpleCommuterApp.java, app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherWarningApp.java, app/tutorials/weather-warning/src/test/java/WeatherWarningAppTest.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/RoadSideUnit.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/ServerUnit.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/VehicleUnit.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/navigation/RoutingNavigationModule.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/navigation/NavigationModule.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/navigation/RoutingModule.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/modules/Navigable.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/modules/Routable.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/navigation/RoutingNavigationModuleTest.java
* In contrast to other unit module interfaces (e.g. perception or communicatin), the navigation related interfaces `INavigationModule` and `IRoutingModule` were misplaced inside the implementation package.
* The interfaces now have been renamed to `NavigationModule` and `RoutingModule` and were moved to `org.eclipse.mosaic.fed.application.app.api.navigation` package to improve consistency.
* The implementation `NavigationModule`, which implements both interfaces, has been renamed to `RoutingNavigationModule`, to 1) avoid name clash with the interface, and 2) to make more clear that it implements both interfaces.
* The method `retrieveAllValidRoutesToTarget(..)` has been removed from `NavigationModule` interface as it was not used and does also makes no sense from a navigation module point …
=> refactor(application): move navigation module interface to api package

bundle/src/assembly/resources/bin/mosaic.bat, bundle/src/assembly/resources/bin/mosaic.sh
In the MOSAIC starter scripts `mosaic.sh` and `mosaic.bat` the path to the Java binary is built with JAVA_HOME if set.
* Resolves internal issue 768
no change in the documentation is required
**Required**
=> feat(bundle): build path to java binary with JAVA_HOME if set

.gitignore
The `.gitignore` added a pattern to exclude all directories named bin. Unfortunately there is one `bin` which should not be ignored. This PR adds an exception for "`bundle/src/assembly/resources/bin/`"
no issue created
docs unaffected
**Required**
=> build: exception for "bundle/../bin/" added

bundle/src/assembly/resources/bin/mosaic.bat, bundle/src/assembly/resources/bin/mosaic.sh
In the MOSAIC starter script `mosaic.sh` additional parameters are not passed correctly to MOSAIC.
This PR fixes that.
* Resolves internal issue 768
no change in the documentation is required
**Required**
=> fix(mosaic.sh): additional parameters not passed correctly

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/errormodels/WallOcclusion.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/WallTree.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/PerceptionModifierTest.java, lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/VectorUtils.java
This PR dramatically improves the speed of Wall Occlusion evaluation
* achieved by a) using a more sensible pre-selection of walls
* b) not using the intersection point calculation from `VectorUtils`
* Resolves issue #<eclipse-mosaic-issue> / internal issue <internal-issue>
**Required**
=> perf(perception): improved speed of Wall Occlusion

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/TrafficManagementCenterUnit.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/TrafficManagementCenterOperatingSystem.java
OS now offers methods to adjust lane assignments and speed assignments for VMS
* Done in context of issue 940, though not very tightly coupled
Changes in the documentation required? Yes, we can mention the helper functions.
**Required**
=> feat: change VMS lane state by os methods

pom.xml
Bump mockito to 5.15.2 to solve problems with JDK 23.
`mvn -site` still does not work with JDK23 since spotbugs plugin would need to be upgraded too. That, however, would raise too many new Spotbugs errors. When we want to upgrade spotbugs, we need to check our spotbugs-configuration.
**Required**
=> build: raise mockito to be compatible with JDK 23

test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/junit/MosaicSimulationRule.java
With this change, we can configure which scenario config is chosen in integration test. We can use a different file name than just always hardcoded `scenario_config.json`
* Addresses internal issue 940
**Required**
=> test: use different scenario config file in integration tests

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/SimulationKernel.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/navigation/CentralNavigationComponent.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassadorTest.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/navigation/CentralNavigationComponentTest.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/VehicleRouting.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/database/DatabaseRouting.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/norouting/NoRouting.java, lib/mosaic-routing/src/test/java/org/eclipse/mosaic/lib/routing/database/DatabaseRoutingTest.java
If SumoAmbassador is started with a SUMO configuration which includes routes, then all routes from SUMO are read via TraCI and send to the RTI. The application ambassador stores these `VehicleRoute`s in an internal cache. If the application simulator already have a route internally with the same ID, it is overridden with the new `VehicleRoute` object coming from SUMO.
There is one major issue: All `VehicleRoute` objects created by SumoAmbassador only contain a list of connection IDs. The list of node IDs is always empty. This leads to the problem, that applications which want to use these routes cannot do stuff like `getOs().getNavigationModule().getCurrentRoute().getLastNodeId()`, which is useful for dynamic route calculation. 
This PR therefore adds the functionality, that the …
=> fix(application): complete VehicleRoute object if it is missing node ids or connection ids

rti/mosaic-starter/MosaicStarter.run.xml
- This PR allows the `MosaicStarter` run-config to work out of the box, by replacing windows-style (i.e., `\`) separators with unix-style separators (i.e., `/`)
- Under windows both separators should work fine
* Relates to internal issue 818
- yes, adjustments are already going on
**Required**
=> fix: Use Unix-style File Separator in Run Config

NOTICE-THIRD-PARTY.md, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/GraphHopperRouting.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/GraphHopperWeighting.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/profile/BikeProfile.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/profile/CarProfile.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/profile/RoutingProfile.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/util/DatabaseGraphLoader.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/util/RoutingProfileManager.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/util/VehicleEncoding.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/graphhopper/util/VehicleEncodingManager.java, lib/mosaic-routing/src/main/java/org/eclipse/mosaic/lib/routing/pt/PtRouting.java, lib/mosaic-routing/src/test/java/org/eclipse/mosaic/lib/routing/graphhopper/GraphHopperWeightingTest.java, lib/mosaic-routing/src/test/java/org/eclipse/mosaic/lib/routing/graphhopper/algorithm/AlternativeRoutesRoutingTest.java, lib/mosaic-routing/src/test/java/org/eclipse/mosaic/lib/routing/graphhopper/algorithm/BellmanFordRoutingTest.java, lib/mosaic-routing/src/test/java/org/eclipse/mosaic/lib/routing/graphhopper/junit/TestGraphRule.java, lib/mosaic-routing/src/test/java/org/eclipse/mosaic/lib/routing/graphhopper/util/DatabaseGraphLoaderTest.java, lib/mosaic-routing/src/test/java/org/eclipse/mosaic/lib/routing/graphhopper/util/TurnCostAnalyzerTest.java, pom.xml
Upgrade graphhopper depedencie from 8.0 to 10.2
* The way how default parsers and encodings were provided changed completely, and is actually more complicate then before. Therefore, we now skip these default factories (now called `DefaultImportRegistry` in Graphhopper) and set the default encodings and parsers depending on the cars and bicycles by our own. 
* This comes with a light refactoring, which introduces the `RoutingProfileManager` and two pre-defined `RoutingProfiles` (`CarRoutingProfile` and `BikeRoutingProfile`) 
* Resolves internal issue 1047
No
**Required**
=> chore(routing): upgrade to GraphHopper 10.2

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/index/providers/TrafficLightIndex.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/SimplePerceptionModuleTest.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/TrafficLightIndexTest.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/trafficlight/TrafficLight.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/trafficlight/TrafficLightGroup.java, lib/mosaic-objects/src/test/java/org/eclipse/mosaic/lib/objects/trafficlight/TrafficLightTest.java
* this PR renames the `id` field in the `TrafficLight` class (which essentially is more of a signal for 1 incoming and 1 outgoing lane) to `index`.
* This change is a sensible change as the `id` really is just an index and not an id, i.e., it's not a unique identifier.
* In general MOSAICs traffic light implementation leads too strongly on SUMOs implementation (i.e., a group of signals makes up a traffic light). In the future we could research how other simulators handle traffic lights and find a good common ground.
* Resolves issue internal issue 1028
As far as I can see, no.
**Required**
=> clean(objects): Renamed id field in TrafficLight object to index

bundle/src/assembly/resources/fed/ns3/Dockerfile, bundle/src/assembly/resources/fed/omnetpp/Dockerfile, lib/mosaic-docker/src/main/java/org/eclipse/mosaic/lib/docker/DockerClient.java, lib/mosaic-docker/src/main/java/org/eclipse/mosaic/lib/docker/DockerCommandLine.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassador.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/ProcessLoggingThread.java, rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/federation/LocalFederationManagement.java, rti/mosaic-starter/pom.xml
This MR solves four issues:
1) Resolves a very old bug/misbehavior which resulted in hiccups when starting OMNeT++ or ns-3 federate. The ambassador would read the provided stdout and errout from the started process to search for the output port and error statements, inside `connectToFederate`. However, simultaneously the ProcessLoggingThread is used to pipe all stdout and errout from the process to the `CommunicationDetails.log` file. The problem here is, that the stream is read twice. To prevent this, we already started the ProcessLoggingThread for the stdout _after_ the call of `connectToFederate`. For the errout, we still started the ProcessLoggingStread before `connectToFederate`, as otherwise, spotting errors in the federate output would be impossible. However, inside …
=> fix(rti): tee output streams before passing them to connectToFederate, copy Dockerfiles to mosaic-starter

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/geo/MutableGeoPoint.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassador.java, lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/CAbstractNetworkAmbassador.java, lib/mosaic-network/src/main/resources/CAbstractNetworkAmbassadorScheme.json, lib/mosaic-network/src/test/java/org/eclipse/mosaic/lib/coupling/AbstractNetworkAmbassadorTest.java, lib/mosaic-network/src/test/java/org/eclipse/mosaic/lib/coupling/CAbstractNetworkAmbassadorTest.java, lib/mosaic-network/src/test/java/org/eclipse/mosaic/lib/coupling/NetworkEntityIdTransformerTest.java, lib/mosaic-network/src/test/resources/ns3_config_with_basestations.json
* Don't use @SerializedName as alternative names are ignored during serialization. With this PR, we switch back so that `FieldNameStrategy` in mosaic-cell can be used instead.
* Added a JSON scheme file for validating `ns3_config.json` and `omnetpp_config.json` configuration files.
* Use custom FieldNameStrategy for CAbstractNetworkAmbassador to shortcut from `latitude` to `lat` and so on.
* Added test to check validation of network-config with base stations.
**To be discussed**
* No issues, fixes main :)
No
**Required**
=> fix(utils): use FieldNameStrategy instead of @SerializedName

lib/mosaic-network/src/main/java/org/eclipse/mosaic/lib/coupling/ClientServerChannel.java
The memory consumption was very high when reading messages from the protobuf (client server channel).
This refactoring now uses a BufferedInputStream (less reads on OS level) and only one instance of CodedInputStream, instead of building a CodedInputStream for every new message read.
* Resolves internal issue 1109
**Required**
=> fix: Use one single CodedInputStream and reduce memory consumption
