README.md, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/communication/CellModuleConfiguration.java, lib/mosaic-interactions/src/main/java/org/eclipse/mosaic/interactions/communication/CellularHandoverUpdates.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/enums/CellTransmissionType.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/addressing/CellMessageRoutingBuilder.java
* This PR only contains some renaming regarding the refactor of the Cell(2)-module
* additionally it fixes a small typo in the README.md
* Resolves internal issue 28
Yes, the cell documentation will be adjusted accordingly.
- [x ] You have read CONTRIBUTING.md carefully.
=> Renaming of the Cell module

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/geo/GeoPolygon.java
Signed-off-by: Pablo Osinaga <pablo.osinaga.arze@fokus.fraunhofer.de>
Follow up to #16.
Internal issue 47.
No.
=> refactor(geomath): GeoPolygon contains

fed/mosaic-cell/src/main/resources/CCellScheme.json, fed/mosaic-cell/src/main/resources/CNetworkScheme.json, fed/mosaic-cell/src/main/resources/CRegionScheme.json, fed/mosaic-environment/src/main/resources/CEnvironmentScheme.json, fed/mosaic-mapping/src/main/resources/CMappingAmbassadorScheme.json, fed/mosaic-sns/src/main/resources/CSnsScheme.json, fed/mosaic-sumo/src/main/resources/CSumoScheme.json, rti/mosaic-rti-core/src/main/java/org/eclipse/mosaic/rti/time/SequentialTimeManagement.java, rti/mosaic-starter/src/main/resources/CScenarioScheme.json
This PR completes the JSON Schema file `CScenarioSchema.json` in order to get included in our documentation website.
* Interal issue 117
=> Completed JSON Schema for scenario_config.json

lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/Database.java
* this PR includes necessary changes to integrate faster import of SUMO net-files
* Solves internal issue 135
* No
=> Consolidate Sumo Import

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/ServerUnit.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/ServerOperatingSystem.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/VehicleRoute.java
Signed-off-by: Moritz Schweppenhäuser <moritz.schweppenhaeuser@fokus.fraunhofer.de>
* This PR adds routing capabilities to servers by giving them  access to an `RoutingModule`
-
=> Added Routing Capabilities to Servers

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Matrix3d.java
This PR makes Matrix3d implement Serializable
https://gitlab.fokus.fraunhofer.de/simulation/mosaic/mosaic-extended/-/issues/133
none
=> Make Matrix3d implement Serializable

lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/DatabaseUtils.java
Signed-off-by: Felix Lutz <felix.lutz@fokus.fraunhofer.de>
The method generateRestrictions() was moved SumoNetFileLoader in mosaic-extended to DatabaseUtils.
* Link to [Eclipse Mosaic repository](https://gitlab.fokus.fraunhofer.de/simulation/mosaic/mosaic-extended/-/issues/150) issue 150
=> Moved method generateRestrictions() to DatabaseUtils

app/tutorials/weather-warning/src/test/java/WeatherWarningAppTest.java, app/tutorials/weather-warning/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/navigation/CentralNavigationComponent.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/VehicleOperatingSystem.java, fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/navigation/CentralNavigationComponentTestRule.java
* This PR introduces a test for the `WeatherWarningApp` this test can be used as an example to test apps
* additionally some minor adjustments are included
* 
* Relates to internal issue 166
* internal documentation has been adapted
=> Test for WeatherWarningApp

fed/mosaic-application/src/test/java/org/eclipse/mosaic/fed/application/ambassador/ApplicationAmbassadorTest.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/vehicle/BatteryData.java
* this PR fixes some namens, that weren't corrected at an earlier stage
* relates to internal issue 202
-
=> Minor qol correction regarding BatteryData

fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/ambassador/spawning/ChargingStationSpawner.java, fed/mosaic-mapping/src/main/java/org/eclipse/mosaic/fed/mapping/config/units/CChargingStation.java, fed/mosaic-mapping/src/main/resources/CMappingAmbassadorScheme.json, fed/mosaic-mapping/src/test/java/org/eclipse/mosaic/fed/mapping/config/InvalidChargingStationTest.java, lib/mosaic-interactions/src/main/java/org/eclipse/mosaic/interactions/electricity/BatteryChargingStart.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/electricity/ChargingSpot.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/electricity/ChargingStationData.java, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/electricity/ChargingType.java
* This PR adjusts the API for charging stations/charging spots to allow for DC charging
* this is achieved by getting rid of the previously used `ChargingMode` and instead using manually configured maximal voltages/current for charging spots
* relates to internal issue 217
=> Extend Battery Model for DC Charging

lib/mosaic-geomath/src/main/java/org/eclipse/mosaic/lib/math/Matrix3d.java, lib/mosaic-geomath/src/test/java/org/eclipse/mosaic/lib/math/Matrix3dTest.java
Resolves #165
* Fixed vector multiplication in Matrix3d
* Added test to prove correct behavior
=> Resolves "Matrix.multply does not match matrix element order"

app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherServerApp.java, app/tutorials/weather-warning/src/main/java/org/eclipse/mosaic/app/tutorial/WeatherWarningApp.java, app/tutorials/weather-warning/src/test/java/WeatherWarningAppTest.java, app/tutorials/weather-warning/src/test/java/org/eclipse/mosaic/app/tutorial/WeatherServerAppTest.java, bundle/src/assembly/resources/etc/runtime.json, bundle/src/assembly/resources/scenarios/Barnim/cell/network.json, bundle/src/assembly/resources/scenarios/Barnim/mapping/mapping_config.json, bundle/src/assembly/resources/scenarios/Barnim/output/output_config.xml, lib/mosaic-objects/src/main/java/org/eclipse/mosaic/lib/objects/v2x/etsi/DenmContent.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/ReleaseBarnimIT.java, test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/ReleaseBarnimLibsumoIT.java
In Barnim tutorial, the WeatherServerApp is no longer implemented as a road side unit, but as a ServerOperatingSystem without a specific geolocation.
* Link to [Eclipse Mosaic repository](https://github.com/eclipse/mosaic/issues) issue
The [Barnim Basic documentation](https://www.eclipse.org/mosaic/tutorials/barnim_basic/) is affected, the necessary changes are already requested.
=> 304 avoid weather rsu

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/LibSumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/bridge/FlowDensityTest.java, pom.xml, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
Upgrades the SumoAmbassador to use the latest SUMO version 1.13.0
* Internal issue 347 
Will be updated with next release
=> feat(sumo): upgrade to SUMO 1.13.0

bundle/src/assembly/resources/fed/ns3/ns3_installer.sh
Upgrades the ns3 federate zip to the latest main.
Internal issue 459
Nothing
=> feat(ns3): use latest ns3 federate in build script

.github/PULL_REQUEST_TEMPLATE.md
Updates the PR template after maintainers discussion
* Resolves  internal issue 447
No
**Required**
=> feat(merge-requests): updated pull request template

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/LibSumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, pom.xml, test/ci/ci-image-mvn-sumo/Dockerfile
Upgrades CI configuration and SUMO ambassador code to use latest release 1.16.0
* Resolves internal issue 550
On next release
**Required**
=> feat(sumo): upgrade to sumo 1.16.0

app/tutorials/example-applications/src/main/java/org/eclipse/mosaic/app/tutorial/traci/SumoTraciInteractionApp.java
* this is a small qol-improvement actually validating the values returned by TraCI in the `SumoTraciInteractionApp`
* the previous comments also were wrong and have been adjusted accordingly
* None
**Required**
=> fix(traci-interaction): SumoTraciInteractionApp now validates values returned by TraCI

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/util/TrafficLightIndexTypeAdapterFactory.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/util/VehicleIndexTypeAdapterFactory.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/util/WallIndexTypeAdapterFactory.java
- just a small (non-functional) fix that changes in which package we look for the `WallIndex` implementation
- none
**Required**
=> fix(percpetion): small fix regarding JsonAdapter for wall index

README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/LibSumoAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/config/CSumo.java, fed/mosaic-sumo/src/main/resources/CSumoScheme.json, pom.xml, test/ci/ci-image-mvn-sumo/README.md
Upgrades SUMO coupling interface to use latest version SUMO.
* Resolves internal issue 608
No
**Required**
=> feat(sumo): upgrade to SUMO 1.17.0

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
* This PR enables compatibility with SUMO version 1.18.0 and bumps version numbers at all relevant places
* Resolves internal issue 623
* will have to be adjusted with next release
**Required**
=> chore(sumo): Enable compatibility with SUMO version 1.18.0

fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/ambassador/LibSumoAmbassador.java
* this small PR also allows Libsumo version 1.18 to be used in pairing with the `LibSumoAmbassador`
* I'm uncertain if we should remove older versions (i.e. 1.16)
* none
* none
**Required**
=> chore(sumo): Updated validation regex for libsumo version

NOTICE-THIRD-PARTY.md, pom.xml
* Upgrades several core dependencies to recent versions, which have been approved by Eclipse IP team (https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab)
* The `pom.xml` includes the issue number (`"approved in #1234"`) in which the depedency jar has been approved by Eclipse Foundation
* Resolves issue #134 
* Resolves internal issue 677
No
**Required**
=> feat: upgrade dependencies

fed/mosaic-output/src/main/java/org/eclipse/mosaic/fed/output/ambassador/OutputAmbassador.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/CommandRegister.java, fed/mosaic-sumo/src/test/java/org/eclipse/mosaic/fed/sumo/config/CSumoTest.java, lib/mosaic-docker/src/main/java/org/eclipse/mosaic/lib/docker/DockerRun.java, lib/mosaic-utils/src/main/java/org/eclipse/mosaic/lib/util/objects/ObjectInstantiation.java, pom.xml
With this PR, Eclipse MOSAIC compiles using JDK 21
* Upgrades Mockito to 5.6.0
* Adjusted some lines due to deprecated API warnings
* Resolves issue #353 / internal issue 701
**Required**
=> feat: build with jdk21

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/perception/errormodels/WallOcclusion.java, lib/mosaic-database/src/main/java/org/eclipse/mosaic/lib/database/persistence/SQLiteAccess.java
* This PR contains minor cleanups found while working on internal issue 715
* Relates to internal issue 715
* None
**Required**
=> cleanup(general): Minor Cleanups

app/tutorials/example-applications/pom.xml, app/tutorials/highway-management/pom.xml, app/tutorials/traffic-light-communication/pom.xml, app/tutorials/weather-warning/pom.xml, bundle/pom.xml, fed/mosaic-application/pom.xml, fed/mosaic-cell/pom.xml, fed/mosaic-environment/pom.xml, fed/mosaic-mapping/pom.xml, fed/mosaic-ns3/pom.xml, fed/mosaic-omnetpp/pom.xml, fed/mosaic-output/pom.xml, fed/mosaic-sns/pom.xml, fed/mosaic-sumo/pom.xml, lib/mosaic-communication/pom.xml, lib/mosaic-database/pom.xml, lib/mosaic-docker/pom.xml, lib/mosaic-geomath/pom.xml, lib/mosaic-interactions/pom.xml, lib/mosaic-network/pom.xml, lib/mosaic-objects/pom.xml, lib/mosaic-routing/pom.xml, lib/mosaic-utils/pom.xml, pom.xml, rti/mosaic-rti-api/pom.xml, rti/mosaic-rti-core/pom.xml, rti/mosaic-starter/pom.xml, test/mosaic-integration-tests/pom.xml
* Adds URL to `github.com/eclipse/mosaic` to all pom.xml files.
* Resolves internal issue 870
No
**Required**
=> build: add URL to all poms

rti/mosaic-rti-api/src/main/java/org/eclipse/mosaic/rti/api/parameters/FederateDescriptor.java, rti/mosaic-starter/src/main/java/org/eclipse/mosaic/starter/MosaicSimulation.java
* This PR includes some minor cleanup tasks noticed during code review
None
**Required**
=> cleanup: Cleanup Tasks in RTI Code

.gitignore, rti/mosaic-starter/.gitignore, rti/mosaic-starter/pom.xml
When running MosaicStarter with IntelliJ and webVisualizer it failed. This PR contains a fix
* Resolves internal issue 888
no
**Required**
=> fix: web visualizer now works out of the box with MosaicStarter

README.md
Adds a simple link/reference to the README, useful for setup IDE
* Addresses internal issue 888
Changes in the documentation required? no.
**Required**
=> docs: link the new documentation page in the README

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/tmc/LaneAreaDetector.java
Adds simple helper function
* Addresses internal issue 940
**Required**
=> feat(app): Make getHaltingVehicles from lastLaneAreaInfo accessible

Jenkinsfile, README.md, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/SumoVersion.java, fed/mosaic-sumo/src/main/java/org/eclipse/mosaic/fed/sumo/bridge/traci/reader/TrafficLightProgramTraciReader.java, test/ci/ci-image-mvn-sumo/Dockerfile, test/ci/ci-image-mvn-sumo/README.md
* Upgrade to support SUMO 1.22.0
* Switch CI to use SUMO 1.22.0 for tests
* Fixed reading traffic light logic via TraCI. Apparently, due to changes in SUMO it now fills the "next" field of traffic light logics, which was not done before and therefore the erroneous implementation of reading the logic was not triggered up until now.
* Resolves internal issue 994
SUMO versions on website documentation will be updated with next MOSAIC release.
**Required**
=> feat(sumo): support SUMO 1.22.0

test/mosaic-integration-tests/src/test/java/org/eclipse/mosaic/test/junit/MosaicSimulationRule.java
Improve error handling in IT's
In context of internal issue 1003
**Required**
=> fix(integration-tests): improve error handling for integration tests

fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/ambassador/simulation/ServerUnit.java, fed/mosaic-application/src/main/java/org/eclipse/mosaic/fed/application/app/api/os/ServerOperatingSystem.java
Also offer chargin station lookup for server unit and not only for EV unit
* Resolves internal issue 1002
**Required**
=> feat(application): offer getChargingStationsInArea(..) for server apps

bundle/src/assembly/resources/fed/ns3/ns3_installer.sh, bundle/src/assembly/resources/fed/omnetpp/omnet_installer.sh
…dencies from ubuntu 22.04
This PR updates premake to some version which is sane against remote code executions, still satisfying all dependencies from ubuntu 22.04
* Resolves internal issue 1025
**Required**
=> fix: update premake to some sane version

bundle/src/assembly/resources/fed/ns3/Dockerfile, bundle/src/assembly/resources/fed/ns3/ns3_installer.sh, fed/mosaic-ns3/src/main/java/org/eclipse/mosaic/fed/ns3/ambassador/Ns3Ambassador.java, rti/mosaic-starter/etc/runtime.json
Improvement of ns3_installer and ns3-federate, in order to straight forward set everything up when developing. Clean up unused things.
* Resolves internal issue 1009
Yes, see MR in Gitlab.
**Required**
=> feat: improve setup ns3 for developers

bundle/src/assembly/resources/fed/omnetpp/Dockerfile, bundle/src/assembly/resources/fed/omnetpp/omnet_installer.sh
With these changes now Omnet 6.1.0 is installed
Thank you @Jacenty00 for the contribution!
* Resolves internal issue 1043
**Required**
=> feat: install omnet 6.1.0

lib/mosaic-utils/src/test/java/org/eclipse/mosaic/lib/util/scheduling/EventSchedulerTest.java
* Use thread-safe list implementation to collect scheduled events in `EventSchedulerTest`.
* Resolves sporadic failures of EventSchedulerTest
* Resolves internal issue 1015
No
**Required**
=> test(utils): fix sporadic failure of EventSchedulerTest

bundle/src/assembly/resources/fed/ns3/ns3_installer.sh, scenarios/bundle/Barnim/ns3/ns3_federate_config.xml, scenarios/bundle/Tiergarten/ns3/ns3_federate_config.xml
This here are only config file changes. The changes themselves are done in the ns3 federate.
* Prepares internal issue 1033
**Required**
=> feat: use wifi not wave (ns3.36.1) 
